# Generated by Django 4.2.1 on 2023-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='rating',
            field=models.SmallIntegerField(default=3),
        ),
    ]
