# Generated by Django 4.2.1 on 2023-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='serviceType',
            field=models.SmallIntegerField(default=1),
        ),
    ]
